name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, manual workflow!
      - name: Run a multi-line script
        run: |
          echo This workflow only runs manually.
          echo Add build, test, or deploy steps here.
